### ISSUE TITLE
Cultural insensitivty

### ISSUE THREAD

**Issue by bronikowski** [jezen/is-thirteen#5]
Thirteen is consider to be unlucky. Many people where killed in slasher movies and other low brow cultural artifacts due the proximity to number 13. Your library should be configurable. Don't expect patch, tho. I'm just here to raise the issue.

https://en.wikipedia.org/wiki/Triskaidekaphobia

**Comment by pohlman** [comment]
In some East Asian cultures, 4 is pronounced similarly to 'death', making it an unlucky number. If you walk into a restaurant, they might instead say, "party for 3 plus 1?" We can apply this logic here:

```
'use strict';
function isTwelvePlusOne(n) {
    return n === 12+1;
}
```

**Comment by eordano** [comment]
Also, it doesn't check for:

https://en.wikipedia.org/wiki/List_of_numbers_in_various_languages

If everyone is ok with this change in behavior, I'm going to go ahead, scrap that list, and send a PR

**Comment by private-face** [comment]
@pohlman I strongly disagree with your suggestion. This approach drags unnecessary attention to cultural differences between people in our society which inevitably leads to a systemic cultural appropriation. From the other hand, keeping the initial name of the module would be dismissive against people with triskaidekaphobia.

I guess the only way out of this problem is to unpublish the module from NPM _immediately_.
